### ISSUE TITLE
--secure fails for most servers

### ISSUE THREAD

**Issue by TilKenneth** [arielf/speedtests#2]
Hello, nice all-in-one project! 

I had to remove --secure due to
```
ERROR: No matched servers: xxxx
my-speedtest.many: failed to get speedtest data for xxxxx
Full output from speedtest-cli:
speed-test by server success rate: 2/10 = 20.00%
```

After I removed it manually, it worked, and;
`speed-test by server success rate: 10/10 = 100.00%`

https://github.com/arielf/speedtests/blob/743df6cec0411401d1cbe85680f3b42c00bb4f77/my-speedtest.many#L86

My change
```perl
    my $output = qx{speedtest --server $server_id --simple};
```

**Comment by arielf** [comment]
Thanks. appreciate the report.
I noticed it myself a while ago; fixed locally, but didn't push.
Should be fixed in master now.

**Comment by arielf** [comment]
fixed in master
